# Copyright (c) 2024, NVIDIA CORPORATION & AFFILIATES. All rights reserved.
#
# Redistribution and use in source and binary forms, with or without
# modification, are permitted provided that the following conditions
# are met:
#  * Redistributions of source code must retain the above copyright
#    notice, this list of conditions and the following disclaimer.
#  * Redistributions in binary form must reproduce the above copyright
#    notice, this list of conditions and the following disclaimer in the
#    documentation and/or other materials provided with the distribution.
#  * Neither the name of NVIDIA CORPORATION nor the names of its
#    contributors may be used to endorse or promote products derived
#    from this software without specific prior written permission.
#
# THIS SOFTWARE IS PROVIDED BY THE COPYRIGHT HOLDERS ``AS IS'' AND ANY
# EXPRESS OR IMPLIED WARRANTIES, INCLUDING, BUT NOT LIMITED TO, THE
# IMPLIED WARRANTIES OF MERCHANTABILITY AND FITNESS FOR A PARTICULAR
# PURPOSE ARE DISCLAIMED.  IN NO EVENT SHALL THE COPYRIGHT OWNER OR
# CONTRIBUTORS BE LIABLE FOR ANY DIRECT, INDIRECT, INCIDENTAL, SPECIAL,
# EXEMPLARY, OR CONSEQUENTIAL DAMAGES (INCLUDING, BUT NOT LIMITED TO,
# PROCUREMENT OF SUBSTITUTE GOODS OR SERVICES; LOSS OF USE, DATA, OR
# PROFITS; OR BUSINESS INTERRUPTION) HOWEVER CAUSED AND ON ANY THEORY
# OF LIABILITY, WHETHER IN CONTRACT, STRICT LIABILITY, OR TORT
# (INCLUDING NEGLIGENCE OR OTHERWISE) ARISING IN ANY WAY OUT OF THE USE
# OF THIS SOFTWARE, EVEN IF ADVISED OF THE POSSIBILITY OF SUCH DAMAGE.

backend: "diffusion"
max_batch_size: 1

dynamic_batching {
 max_queue_delay_microseconds: 100000
}

input [
  {
    name: "prompt"
    data_type: TYPE_STRING
    dims: [1]
  },
  {
    name: "negative_prompt"
    data_type: TYPE_STRING
    dims: [1]
    optional: true
  }
]
output [
  {
    name: "generated_image"
    data_type: TYPE_UINT8
    dims: [ -1, -1, -1]
  }
]

instance_group [
  { count: 1
    kind: KIND_GPU
    gpus: [0]
  }
]

parameters[
{
  key: "onnx_opset"
  value: {
    string_value: "18"
  }
},
{
  key: "image_height"
  value: {
    string_value: "1024"
  }
},
{
  key: "image_width"
  value: {
    string_value: "1024"
  }
},
{
  key: "steps"
  value: {
    string_value: "30"
  }
},
{
  key: "scheduler"
  value: {
    string_value: ""
  }
},
{
  key: "guidance_scale"
  value: {
    string_value: "5.0"
  }
},
{
  key: "seed"
  value: {
    string_value: ""
  }
},
{
  key: "version"
  value: {
    string_value: "xl-1.0"
  }
},
{
  key: "force_engine_build"
  value: {
    string_value: ""
  }
}

]
