{
 "title": "Inference Metrics",
 "time": { "from": "now-9m", "to": "now" },
 "refresh": "6s",
 "panels": [
  { "title": "Cluster Health", "type": "row", "gridPos": { "h": 1, "w": 24, "x": 0, "y": 0 } },
  {
   "title": "Node CPU Utilization",
   "type": "timeseries",
   "gridPos": { "h": 5, "w": 12, "x": 0, "y": 1 },
   "fieldConfig": { "defaults": { "unit": "percentunit" } },
   "targets": [
    {
     "expr": "instance:node_cpu_utilisation:rate5m",
     "legendFormat": "{{instance}}"
    }
   ]
  },
  {
   "title": "Node Memory Utilization",
   "type": "timeseries",
   "gridPos": { "h": 5, "w": 12, "x": 12, "y": 1 },
   "fieldConfig": { "defaults": { "unit": "percentunit" } },
   "targets": [
    {
     "expr": "1-(node_memory_MemFree_bytes/node_memory_MemTotal_bytes)",
     "legendFormat": "{{instance}}"
    }
   ]
  },
  { "title": "Triton Metrics", "type": "row", "gridPos": { "h": 1, "w": 24, "x": 0, "y": 6 } },
  {
   "title": "Queue : Compute Ratio",
   "type": "timeseries",
   "gridPos": { "h": 5, "w": 12, "x": 0, "y": 7 },
   "fieldConfig": { "defaults": { "unit": "percentunit" } },
   "targets": [
    {
     "expr": "max by(job) (triton:queue_compute:ratio)",
     "legendFormat": "{{job}}"
    }
   ]
  },
  {
   "title": "Request Duration",
   "type": "timeseries",
   "gridPos": { "h": 5, "w": 12, "x": 12, "y": 7 },
   "fieldConfig": { "defaults": { "unit": "µs" } },
   "targets": [
    {
     "expr": "max by(job) (triton:request_duration:average)",
     "legendFormat": "maximum({{job}})"
    },
    {
     "expr": "avg by(job) (triton:request_duration:average)",
     "legendFormat": "average({{job}})"
    },
    {
     "expr": "min by(job) (triton:request_duration:average)",
     "legendFormat": "minimum({{job}})"
    }
   ]
  },
  {
   "title": "Requests / Second",
   "type": "timeseries",
   "gridPos": { "h": 5, "w": 12, "x": 0, "y": 12 },
   "fieldConfig": { "defaults": { "unit": "none" } },
   "targets": [
    {
     "expr": "sum by(job) (rate(nv_inference_request_success[1m]))",
     "legendFormat": "{{job}}(success)"
    },
    {
     "expr": "sum by(job) (rate(nv_inference_request_failure[1m]))",
     "legendFormat": "{{job}}(failure)"
    }
   ]
  },
  {
   "title": "I/O Duration",
   "type": "timeseries",
   "gridPos": { "h": 5, "w": 12, "x": 12, "y": 12 },
   "fieldConfig": { "defaults": { "unit": "µs" } },
   "targets": [
    {
     "expr": "sum by(job) (rate(nv_inference_compute_input_duration_us[1m])/clamp_min(rate(nv_inference_request_success[1m]),1))",
     "legendFormat": "{{job}}(input)"
    },
    {
     "expr": "sum by(job) (rate(nv_inference_compute_output_duration_us[1m])/clamp_min(rate(nv_inference_request_success[1m]),1))",
     "legendFormat": "{{job}}(output)"
    }
   ]
  },
  { "title": "TRT-LLM Metrics", "type": "row", "gridPos": { "h": 1, "w": 24, "x": 0, "y": 17 } },
  {
   "title": "TRT-LLM General",
   "type": "timeseries",
   "gridPos": { "h": 5, "w": 8, "x": 0, "y": 18 },
   "targets": [
    {
     "expr": "avg by(job) (rate(nv_trt_llm_general_metrics[1m]))",
     "legendFormat": "{{job}}"
    }
   ]
  },
  {
   "title": "TRT-LLM In-Flight Batcher",
   "type": "timeseries",
   "gridPos": { "h": 5, "w": 8, "x": 8, "y": 18 },
   "fieldConfig": { "defaults": { "unit": "none" } },
   "targets": [
    {
     "expr": "sum by(job) (nv_trt_llm_inflight_batcher_metrics)",
     "legendFormat": "__auto"
    }
   ]
  },
  {
   "title": "TRT-LLM Requests",
   "type": "timeseries",
   "gridPos": { "h": 5, "w": 8, "x": 16, "y": 18 },
   "targets": [
    {
     "expr": "sum by(job) (rate(nv_trt_llm_request_metrics[1m]))",
     "legendFormat": "{{job}}"
    }
   ]
  },
  { "title": "GPU Metrics", "type": "row", "gridPos": { "h": 1, "w": 24, "x": 0, "y": 23 } },
  {
   "title": "GPU Utilization",
   "type": "timeseries",
   "gridPos": { "h": 7, "w": 6, "x": 0, "y": 24 },
   "fieldConfig": { "defaults": { "unit": "percent" } },
   "targets": [
    {
     "expr": "max by(Hostname,modelName,gpu) (avg_over_time(DCGM_FI_DEV_GPU_UTIL[$__interval]))",
     "legendFormat": "{{modelName}}/{{gpu}}"
    }
   ]
  },
  {
   "title": "GPU Temperature",
   "type": "timeseries",
   "gridPos": { "h": 7, "w": 6, "x": 6, "y": 24 },
   "fieldConfig": { "defaults": { "unit": "celsius" } },
   "targets": [
    {
     "expr": "avg by(Hostname,modelName,gpu) (avg_over_time(DCGM_FI_DEV_GPU_TEMP[$__interval]))",
     "legendFormat": "{{modelName}}/{{gpu}}"
    }
   ]
  },
  {
   "title": "GPU Power Usage",
   "type": "timeseries",
   "gridPos": { "h": 7, "w": 6, "x": 12, "y": 24 },
   "fieldConfig": { "defaults": { "unit": "watt" } },
   "targets": [
    {
     "expr": "avg by(Hostname,modelName,gpu) (avg_over_time(DCGM_FI_DEV_POWER_USAGE[$__interval]))",
     "legendFormat": "{{modelName}}/{{gpu}}"
    }
   ]
  },
  {
   "title": "GPU Memory Utilization",
   "type": "timeseries",
   "gridPos": { "h": 7, "w": 6, "x": 18, "y": 24 },
   "fieldConfig": { "defaults": { "unit": "percentunit" } },
   "targets": [
    {
     "expr": "max by(Hostname,modelName,gpu) (DCGM_FI_DEV_FB_USED/(DCGM_FI_DEV_FB_USED+DCGM_FI_DEV_FB_FREE))",
     "legendFormat": "{{modelName}}/{{gpu}}"
    }
   ]
  }
 ]
}