# coding: utf-8

"""
    OpenAI API

    The OpenAI REST API. Please see https://platform.openai.com/docs/api-reference for more details.

    The version of the OpenAPI document: 2.0.0
    Generated by OpenAPI Generator (https://openapi-generator.tech)

    Do not edit the class manually.
"""  # noqa: E501


from __future__ import annotations

import json
import pprint
import re  # noqa: F401
from typing import Any, ClassVar, Dict, List, Optional

from pydantic import BaseModel, ConfigDict, Field, StrictInt, StrictStr, field_validator

from openapi_server.models.chat_completion_response_message import (
    ChatCompletionResponseMessage,
)
from openapi_server.models.create_chat_completion_response_choices_inner_logprobs import (
    CreateChatCompletionResponseChoicesInnerLogprobs,
)

try:
    from typing import Self
except ImportError:
    from typing_extensions import Self


class CreateChatCompletionResponseChoicesInner(BaseModel):
    """
    CreateChatCompletionResponseChoicesInner
    """  # noqa: E501

    finish_reason: StrictStr = Field(
        description="The reason the model stopped generating tokens. This will be `stop` if the model hit a natural stop point or a provided stop sequence, `length` if the maximum number of tokens specified in the request was reached, `content_filter` if content was omitted due to a flag from our content filters, `tool_calls` if the model called a tool, or `function_call` (deprecated) if the model called a function. "
    )
    index: StrictInt = Field(
        description="The index of the choice in the list of choices."
    )
    message: ChatCompletionResponseMessage
    logprobs: Optional[CreateChatCompletionResponseChoicesInnerLogprobs]
    __properties: ClassVar[List[str]] = [
        "finish_reason",
        "index",
        "message",
        "logprobs",
    ]

    @field_validator("finish_reason")
    def finish_reason_validate_enum(cls, value):
        """Validates the enum"""
        if value not in (
            "stop",
            "length",
            "tool_calls",
            "content_filter",
            "function_call",
        ):
            raise ValueError(
                "must be one of enum values ('stop', 'length', 'tool_calls', 'content_filter', 'function_call')"
            )
        return value

    model_config = {
        "populate_by_name": True,
        "validate_assignment": True,
        "protected_namespaces": (),
    }

    def to_str(self) -> str:
        """Returns the string representation of the model using alias"""
        return pprint.pformat(self.model_dump(by_alias=True))

    def to_json(self) -> str:
        """Returns the JSON representation of the model using alias"""
        # TODO: pydantic v2: use .model_dump_json(by_alias=True, exclude_unset=True) instead
        return json.dumps(self.to_dict())

    @classmethod
    def from_json(cls, json_str: str) -> Self:
        """Create an instance of CreateChatCompletionResponseChoicesInner from a JSON string"""
        return cls.from_dict(json.loads(json_str))

    def to_dict(self) -> Dict[str, Any]:
        """Return the dictionary representation of the model using alias.

        This has the following differences from calling pydantic's
        `self.model_dump(by_alias=True)`:

        * `None` is only added to the output dict for nullable fields that
          were set at model initialization. Other fields with value `None`
          are ignored.
        """
        _dict = self.model_dump(
            by_alias=True,
            exclude={},
            exclude_none=True,
        )
        # override the default output from pydantic by calling `to_dict()` of message
        if self.message:
            _dict["message"] = self.message.to_dict()
        # override the default output from pydantic by calling `to_dict()` of logprobs
        if self.logprobs:
            _dict["logprobs"] = self.logprobs.to_dict()
        # set to None if logprobs (nullable) is None
        # and model_fields_set contains the field
        if self.logprobs is None and "logprobs" in self.model_fields_set:
            _dict["logprobs"] = None

        return _dict

    @classmethod
    def from_dict(cls, obj: Dict) -> Self:
        """Create an instance of CreateChatCompletionResponseChoicesInner from a dict"""
        if obj is None:
            return None

        if not isinstance(obj, dict):
            return cls.model_validate(obj)

        _obj = cls.model_validate(
            {
                "finish_reason": obj.get("finish_reason"),
                "index": obj.get("index"),
                "message": ChatCompletionResponseMessage.from_dict(obj.get("message"))
                if obj.get("message") is not None
                else None,
                "logprobs": CreateChatCompletionResponseChoicesInnerLogprobs.from_dict(
                    obj.get("logprobs")
                )
                if obj.get("logprobs") is not None
                else None,
            }
        )
        return _obj
