name: "tokenizer"
max_batch_size: 0
backend: "python"

input [
{
    name: "TEXT"
    data_type: TYPE_STRING
    dims: [ -1 ]
}
]

output [
{
    name: "input_ids"
    data_type: TYPE_INT64
    dims: [-1, 256]
},
{
    name: "attention_mask"
    data_type: TYPE_INT64
    dims: [-1, 256]
},
{
    name: "token_type_ids"
    data_type: TYPE_INT64
    dims: [ -1, 256 ]
  }
]
