apiVersion: v1
kind: PersistentVolume
metadata:
  name: efs-pv-2
spec:
  capacity:
    storage: 200Gi
  volumeMode: Filesystem
  accessModes:
    - ReadWriteMany
  persistentVolumeReclaimPolicy: Retain
  storageClassName: efs-sc-1
  csi:
    driver: efs.csi.aws.com
    volumeHandle: fs-0d5ec63b9f8ebb2db
