ARG BASE_IMAGE=nvcr.io/nvidia/tritonserver
ARG BASE_IMAGE_TAG=23.09-py3

FROM ${BASE_IMAGE}:${BASE_IMAGE_TAG} as triton-ray

RUN pip install -U ray[all]==2.7
RUN pip install /opt/tritonserver/python/tritonserver-2.38.0-py3-none-any.whl
RUN pip install git+https://github.com/NVIDIA/TensorRT-LLM.git
RUN mkdir /usr/local/lib/python3.10/dist-packages/tensorrt_llm/libs/
RUN cp /opt/tritonserver/backends/tensorrtllm/* /usr/local/lib/python3.10/dist-packages/tensorrt_llm/libs/
RUN cp /app/tensorrt_llm/tensorrt_llm/libs/* /usr/local/lib/python3.10/dist-packages/tensorrt_llm/libs/
