name: "python_vit"
backend: "python"
max_batch_size: 8

input [
  {
    name: "image"
    data_type: TYPE_FP32
    dims: [-1, -1, -1]
  }
]
output [
  {
    name: "last_hidden_state"
    data_type: TYPE_FP32
    dims: [-1, -1]
  }
]

instance_group [
  {
    kind: KIND_GPU
  }
]
